### ISSUE TITLE
Use . instead of source in shell scripts

### ISSUE THREAD

**Issue by gucharbon** [tiangolo/full-stack-fastapi-postgresql#97] opened 2020-01-07 21:13 UTC
I'm using 18.04.3 LTS (Bionic Beaver) and python 3.7.5
I just created my own repository using cookiecutter.

I ran the script `./scripts/build-push.sh` and received the error below:

```
(venv) monsoon@-bash4.4:/c/Users/monsoon/fastapi/webdemo(21:19:57)$ ./scripts/build-push.sh
./scripts/build-push.sh: 6: ./scripts/build-push.sh: source: not found
```

After taking a look at [the template](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/scripts/build-push.sh) I saw that `/bin/sh` is specified in shebang:

```sh
#! /usr/bin/env sh

# Exit in case of error
set -e
```

 Ubuntu uses `/bin/dash` in place of`/bin/sh` and not `/bin/bash`. [Ubuntu Wiki](https://wiki.ubuntu.com/DashAsBinSh#source) states that:
>The source builtin is a bashism (related checkbashisms warning text: 'source' instead of '.'). Write this simply as . instead. 

Isn't there anybody on Ubuntu or Debian which tried to run the scripts and had this error? I searched existing issue but found none.

Edit: I just saw in the README that user should use `bash`  to start scripts (as in the example: `TAG=prod FRONTEND_ENV=production bash ./scripts/build-push.sh`) but I still feel that this `.` should be used instead of `source` to be coherent with shebang and to allow usage of `TAG=prod FRONTEND_ENV=production ./scripts/build-push.sh`.

Anyway thanks for the awesome work :)

**Comment by Shackelford-Arden** [comment] 2020-03-22 04:37
@gucharbon While that documentation you provided does indicate the use of `dash` on Ubuntu based systems, if you run the command as shown in the shebang:

```shell
/usr/bin/env sh
```

On an Ubuntu system (tested on Ubuntu 18.04.4) you'll find that this works just fine.

As the documentation page you referenced indicates in the second paragraph from the top:

> The default login shell remains bash. Opening a terminal from the menu or shortcut [crtl-alt-t] provides interactive bash. A script run from the desktop or file manager, through the dialogue 'run in terminal' will execute as POSIX dash.

The benefit of specifying the `/usr/bin/env sh` at the beginning tells the system to use `sh` instead of whatever shell you yourself are actively using at the time of script execution.

So, I don't think it's helpful to make the change from `source` to `.` here.

**Comment by gucharbon** [comment] 2020-03-23 08:19
@Shackelford-Arden 
I don't get your comment. Using `source` command in a script with `/usr/bin/env sh` sheebang will result in  a failure if you're running on Ubuntu Bionic (18.04).

Unless you explicitely start the script with `bash <script_name>`.

IMO it is clearly a bug to have a script using `sh` in sheebang and still use `source` later in the script.

**Comment by Shackelford-Arden** [comment] 2020-03-23 15:45
My apologies, I managed to test incorrectly when I was looking at this. Guess that's what I get for moving too quickly :) You're correct that `source` does not work as intended in this script.

**Comment by StephenBrown2** [comment] 2020-03-23 17:23
Shouldn't it be `/usr/bin/env bash`, then?

**Comment by gucharbon** [comment] 2020-03-23 19:31
I think we are thinking a lot for a really small issue 😄 

@StephenBrown2 I guess there is no right or wrong between using `/usr/bin/env bash` in sheebang or using `.` instead of `source`.

I don't really care, and I don't think people will want to run the scripts in environments without bash installed by default (like alpine linux for example). 

But still, I think that between 2 working solutions, the most portable should always be prefered.

**Comment by StephenBrown2** [comment] 2020-03-23 22:03
+1 for `.` then

**Comment by tiangolo** [comment] 2020-04-17 06:06
Thanks for the discussion here everyone!

Yeah, agreed that `source` is a bit more readable, but `.` should work in more environments and that wins in the end :smile: 

Thanks for the PR with the fix @gucharbon ! :rocket:

**Closed** 2020-04-28 00:10 UTC
