### ISSUE TITLE
Can't login while Backend is running fine

### ISSUE THREAD

**Issue by awmar1** [tiangolo/full-stack-fastapi-postgresql#415] opened 2021-08-27 15:05 UTC
I followed the wiki page to install:

```
    pip install cookiecutter
    cookiecutter https://github.com/tiangolo/full-stack-fastapi-postgresql
```

everything is running fine ( after fixing the flower versioning issue ) now I can't log in at `http://my.ip/login` while I can enter the backed through `http://my.ip/docs` and test the credentials.

at the console I get `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost/api/v1/login/access-token. (Reason: CORS request did not succeed).` whenever I try to login or reset password through the same form.

any idea?

**Comment by sbourke** [comment] 2021-08-27 23:27
Seems like a duplicate of https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/372

**Closed** 2021-08-29 23:58 UTC

**Comment by sbourke** [comment] 2021-08-30 06:44
Awmar can you share your .env file.

**Comment by awmar1** [comment] 2021-08-30 19:20
@sbourke sure, did you check my comment on [this](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/372) thread?

`DOMAIN=myip`  was localhost which was causing the issue with the frontend not sure though the issue was with this `.env` file or the frontend one. 
```

# DOMAIN=local.dockertoolbox.tiangolo.com
# DOMAIN=localhost.tiangolo.com
# DOMAIN=dev.projectname.com

STACK_NAME=projectname-com

TRAEFIK_PUBLIC_NETWORK=traefik-public
TRAEFIK_TAG=projectname.com
TRAEFIK_PUBLIC_TAG=traefik-public

DOCKER_IMAGE_BACKEND=backend
DOCKER_IMAGE_CELERYWORKER=celeryworker
DOCKER_IMAGE_FRONTEND=frontend

# Backend
BACKEND_CORS_ORIGINS=["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.projectname.com", "https://stag.projectname.com", "https://projectname.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]
PROJECT_NAME=projectname
SECRET_KEY=changethis
FIRST_SUPERUSER=admin@projectname.com
FIRST_SUPERUSER_PASSWORD=changethis
SMTP_TLS=True
SMTP_PORT=587
SMTP_HOST=
SMTP_USER=
SMTP_PASSWORD=
EMAILS_FROM_EMAIL=info@projectname.com

USERS_OPEN_REGISTRATION=False

SENTRY_DSN=

# Flower
FLOWER_BASIC_AUTH=admin:changethis

# Postgres
POSTGRES_SERVER=db
POSTGRES_USER=postgres
POSTGRES_PASSWORD=changethis
POSTGRES_DB=app

# PgAdmin
PGADMIN_LISTEN_PORT=5050
PGADMIN_DEFAULT_EMAIL=admin@projectname.com
PGADMIN_DEFAULT_PASSWORD=changethis

```

btw would it be too much to ask you to check [this](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/416)?
